package:
  name: ctags
  version: 6.2.0
  epoch: 0
  description: "A maintained ctags implementation"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      license: GPL-2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - jansson-dev
      - pkgconf
      - pkgconf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/universal-ctags/ctags/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 313c864bb19c7da79aea77b94db1bb44d14c1f88b992285d7ea8968b3cbc125f

  - name: Autogen
    runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --program-prefix=universal- \
        --enable-json

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: universal-ctags/ctags
    strip-prefix: "v"
