package:
  name: redis_exporter
  version: 1.74.0
  epoch: 0
  description: "Prometheus Exporter for Redis Metrics"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: 'Copyright (c) 2016 Oliver'
      license: 'MIT License'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/oliver006/redis_exporter/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 5d7564de2359c5cb8fd27f80ab22f22e687391bfca05f4968d2e3a2cd1c65268

  - uses: go/build
    with:
      packages: main.go
      ldflags: "-s -w -extldflags \"-static\""
      prefix: /usr/local
      output: redis_exporter

update:
  enabled: true
  github:
    identifier: oliver006/redis_exporter
    strip-prefix: "v"
